# Generated by Django 5.2.5 on 2025-08-22 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FEMB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='unknown', max_length=20)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(default='unknown', max_length=20)),
                ('tray_id', models.CharField(max_length=20)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('femb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.femb')),
            ],
        ),
    ]
