# Generated by Django 5.2.5 on 2025-08-27 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fe',
            name='femb_pos',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='femb',
            name='version',
            field=models.CharField(default='IO-1865-1K', max_length=20),
        ),
        migrations.AlterField(
            model_name='fe',
            name='status',
            field=models.CharField(default='testing', max_length=20),
        ),
        migrations.AlterField(
            model_name='femb',
            name='serial_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='femb',
            name='status',
            field=models.CharField(default='testing', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='femb',
            unique_together={('version', 'serial_number')},
        ),
        migrations.CreateModel(
            name='ADC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(default='testing', max_length=20)),
                ('tray_id', models.CharField(blank=True, max_length=20, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('femb_pos', models.CharField(blank=True, max_length=2, null=True)),
                ('femb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.femb')),
            ],
        ),
        migrations.CreateModel(
            name='COLDATA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(default='testing', max_length=20)),
                ('tray_id', models.CharField(blank=True, max_length=20, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('femb_pos', models.CharField(blank=True, max_length=2, null=True)),
                ('femb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.femb')),
            ],
        ),
    ]
