# Generated by Django 5.2.5 on 2025-09-02 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fe_femb_pos_femb_version_alter_fe_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FEMB_TEST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('test_type', models.CharField(max_length=10)),
                ('test_env', models.CharField(max_length=10)),
                ('report_filename', models.CharField(max_length=400)),
                ('femb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.femb')),
            ],
        ),
    ]
