# Generated by Django 5.2.5 on 2025-09-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_femb_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='femb_test',
            name='site',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='femb_test',
            name='status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
