# Generated by Django 5.2.5 on 2026-01-06 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_femb_test_site_femb_test_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CABLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(default='testing', max_length=20)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CABLE_TEST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('test_type', models.CharField(max_length=10)),
                ('test_env', models.CharField(max_length=10)),
                ('report_filename', models.CharField(max_length=400)),
                ('site', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(blank=True, default='', max_length=20)),
                ('cable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cable')),
            ],
        ),
    ]
