# Generated by Django 5.2.5 on 2026-01-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cable_cable_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='batch_number',
            field=models.IntegerField(default=0),
        ),
    ]
