# Generated by Django 5.2.5 on 2026-05-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_models_to_pascalcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='larasic',
            name='tray_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
