# Generated by Django 5.2.5 on 2026-05-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_larasic_tray_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='larasic',
            name='cold_tested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='larasic',
            name='warm_tested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='larasic',
            name='status',
            field=models.CharField(default='rts-tested', max_length=20),
        ),
    ]
