# Generated by Django 5.2.5 on 2026-05-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_larasic_cold_tested_at_larasic_warm_tested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='larasic',
            name='hwdb_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='larasic',
            name='is_in_hwdb',
            field=models.BooleanField(default=False),
        ),
    ]
