# Generated by Django 5.2.5 on 2026-05-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_larasic_hwdb_checked_at_larasic_is_in_hwdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='larasic',
            name='qc_tests_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
