# Generated by Django 5.2.5 on 2026-05-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_larasic_qc_tests_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='larasic',
            name='cold_csv_attached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='larasic',
            name='warm_csv_attached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
