# Generated by Django 5.2.5 on 2026-06-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_larasic_csv_attached_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='femb',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
