# Generated by Django 5.2.5 on 2026-05-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrayCsvCache',
            fields=[
                ('tray_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dir_mtime', models.FloatField()),
                ('csvs', models.JSONField(default=dict)),
                ('scanned_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
