# Generated by Django 5.2.5 on 2026-06-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwdb', '0002_traycsvcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='HwdbSyncState',
            fields=[
                ('family', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('chips_total', models.PositiveIntegerField(default=0)),
                ('chips_new', models.PositiveIntegerField(default=0)),
                ('chips_disappeared', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='HwdbChip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(choices=[('larasic', 'LArASIC'), ('coldadc', 'ColdADC'), ('coldata', 'COLDATA')], db_index=True, max_length=10)),
                ('serial_number', models.CharField(max_length=50)),
                ('part_id', models.CharField(max_length=50)),
                ('part_type_id', models.CharField(max_length=20)),
                ('latest_rt_test_at', models.DateTimeField(blank=True, null=True)),
                ('latest_ln_test_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['family', 'latest_rt_test_at'], name='hwdb_hwdbch_family_4663c3_idx'), models.Index(fields=['family', 'latest_ln_test_at'], name='hwdb_hwdbch_family_62defd_idx')],
                'unique_together': {('family', 'serial_number')},
            },
        ),
    ]
