# Generated by Django 5.2.5 on 2026-06-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwdb', '0003_hwdbsyncstate_hwdbchip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentTypeNode',
            fields=[
                ('part_type_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('project', models.CharField(default='D', max_length=4)),
                ('system_id', models.PositiveIntegerField(db_index=True)),
                ('system_name', models.CharField(max_length=100)),
                ('subsystem_id', models.PositiveIntegerField()),
                ('subsystem_name', models.CharField(max_length=100)),
                ('component_type_name', models.CharField(max_length=200)),
                ('full_name', models.CharField(blank=True, default='', max_length=300)),
                ('n_components', models.PositiveIntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['system_id', 'subsystem_id', 'component_type_name'],
            },
        ),
        migrations.CreateModel(
            name='HierarchySyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('systems_count', models.PositiveIntegerField(default=0)),
                ('nodes_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
        ),
    ]
