# Generated by Django 5.2.5 on 2026-06-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwdb', '0004_componenttypenode_hierarchysyncstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='componenttypenode',
            name='n_tests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='componenttypenode',
            name='tests_sync_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='componenttypenode',
            name='tests_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HwdbTestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type_id', models.CharField(db_index=True, max_length=20)),
                ('part_id', models.CharField(max_length=50)),
                ('test_type_name', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['part_type_id', 'created'], name='hwdb_hwdbte_part_ty_a5946d_idx')],
            },
        ),
    ]
