# Generated by Django 5.2.5 on 2026-06-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwdb', '0005_componenttypenode_n_tests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HwdbComponentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type_id', models.CharField(db_index=True, max_length=20)),
                ('part_id', models.CharField(max_length=50)),
                ('created', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['part_type_id', 'created'], name='hwdb_hwdbco_part_ty_8d3b4d_idx')],
            },
        ),
    ]
