# Generated by Django 5.2.5 on 2026-06-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwdb', '0006_hwdbcomponentevent'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hwdbcomponentevent',
            name='hwdb_hwdbco_part_ty_8d3b4d_idx',
        ),
        migrations.AddField(
            model_name='hwdbcomponentevent',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hwdbcomponentevent',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='hwdbcomponentevent',
            index=models.Index(fields=['part_type_id', 'updated'], name='hwdb_hwdbco_part_ty_4aeadc_idx'),
        ),
    ]
