# Generated by Django 5.2.5 on 2026-06-29 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hwdb', '0007_remove_hwdbcomponentevent_hwdb_hwdbco_part_ty_8d3b4d_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComponentTypeNode',
        ),
        migrations.DeleteModel(
            name='HierarchySyncState',
        ),
        migrations.DeleteModel(
            name='HwdbComponentEvent',
        ),
        migrations.DeleteModel(
            name='HwdbTestEvent',
        ),
    ]
