"""Hierarchy chart specs: semantic spec → laid-out SVG model (#55/#57).

One YAML per chart in ``chart_specs/`` (file name = chart id). A spec is
semantic — nodes, tree edges (child → parent) and cable edges, with NO
coordinates. Geometry comes from a sibling **layout overlay**
(``<id>.layout.yaml``, generated by ``extract_chart --layout``): PDF-faithful
box positions, band strips and loose annotation texts, regenerated wholesale
when the consortium updates the chart PDF — the hand-curated spec never
churns. Edges are routed orthogonally between the true positions. Charts
without an overlay (and spec nodes missing from it) fall back to the house
layout: parent box above an indented vertical stack of children, root
subtrees left-to-right inside band rows. The label → part_type_id mapping is
a separate overlay (#58), not part of the spec.
"""

from __future__ import annotations

import functools
from pathlib import Path

import yaml

CHART_DIR = Path(__file__).parent / "chart_specs"

BOX_H = 18.0
CHAR_W = 5.2          # ~IBM Plex Sans at font-size 10
NOTE_CHAR_W = 4.7     # annotations render at font-size 9
BOX_PAD = 12.0
MIN_BOX_W = 36.0
INDENT = 16.0         # child stack indent under its parent
VGAP = 5.0            # vertical gap between stacked boxes
TRUNK_X = 7.0         # bracket trunk offset inside the parent's left edge
ROOT_GAP = 40.0       # gap between root subtrees in a band row
BAND_PAD = 14.0       # padding above/below a band row's content
EMPTY_BAND_H = 40.0   # strip height for a band with no nodes (label only)
MARGIN = 30.0
LABEL_W = 170.0       # content offset in a labeled band (room for the title)
CABLE_LANE = 24.0     # how far right of the boxes a cable elbow runs
LANE_STEP = 7.0       # stagger between cable lanes sharing a corridor
STACK_TOL = 60.0      # child x-offset that still reads as the stacked idiom


def chart_ids() -> list[str]:
    return sorted(p.stem for p in CHART_DIR.glob("*.yaml")
                  if not p.stem.endswith(".layout"))


@functools.lru_cache(maxsize=None)
def svg_chart(chart_id: str) -> dict:
    """Template-ready model of one chart. Callers must not mutate it."""
    with open(CHART_DIR / f"{chart_id}.yaml") as f:
        spec = yaml.safe_load(f) or {}
    overlay_path = CHART_DIR / f"{chart_id}.layout.yaml"
    overlay = None
    if overlay_path.exists():
        with open(overlay_path) as f:
            overlay = yaml.safe_load(f) or {}
    return _build(chart_id, spec, overlay)


@functools.lru_cache(maxsize=None)
def type_mapping(chart_id: str, instance: str) -> dict[str, list[str]]:
    """Hand-curated node id → part type ids for one chart + instance (#58),
    from ``<id>.mapping.yaml``. Empty when the file or instance is absent."""
    path = CHART_DIR / f"{chart_id}.mapping.yaml"
    if not path.exists():
        return {}
    with open(path) as f:
        data = yaml.safe_load(f) or {}
    block = (data.get("instances") or {}).get(instance) or {}
    return {nid: [v] if isinstance(v, str) else list(v)
            for nid, v in block.items()}


def _box_w(label: str) -> float:
    return max(MIN_BOX_W, BOX_PAD + CHAR_W * len(label))


def _route(c: dict, p: dict) -> list[tuple]:
    """Orthogonal connector from child box c into parent box p, using their
    real positions: same-row edges run horizontally between facing sides;
    the PDF's stacked idiom gets its bracket; everything else takes an
    L-shaped elbow into the parent's near horizontal edge."""
    c_x2, c_y2 = c["x"] + c["w"], c["y"] + c["h"]
    p_x2, p_y2 = p["x"] + p["w"], p["y"] + p["h"]
    if c["y"] < p_y2 and p["y"] < c_y2:  # same row
        if c["x"] >= p_x2:
            return [(c["x"], c["cy"]), (p_x2, c["cy"])]
        return [(c_x2, c["cy"]), (p["x"], c["cy"])]
    entry_y = p_y2 if c["y"] >= p_y2 else p["y"]  # parent's near edge
    if p["x"] - 4 <= c["x"] <= p["x"] + STACK_TOL and c["y"] >= p_y2:
        tx = max(p["x"] + 4, min(c["x"] - 9, p_x2 - 4))
        return [(c["x"], c["cy"]), (tx, c["cy"]), (tx, entry_y)]
    if p["x"] <= c["cx"] <= p_x2:
        exit_y = c["y"] if c["y"] >= p_y2 else c_y2
        return [(c["cx"], exit_y), (c["cx"], entry_y)]
    sx = c["x"] if p["cx"] < c["cx"] else c_x2
    return [(sx, c["cy"]), (p["cx"], c["cy"]), (p["cx"], entry_y)]


def _build(chart_id: str, spec: dict, overlay: dict | None = None) -> dict:
    nodes = {n["id"]: dict(n) for n in spec.get("nodes") or []}
    if len(nodes) != len(spec.get("nodes") or []):
        raise ValueError(f"chart {chart_id}: duplicate node ids")

    # Split edges; tree edges give each child exactly one parent.
    parent: dict[str, str] = {}
    cables = []
    for e in spec.get("edges") or []:
        if e["from"] not in nodes or e["to"] not in nodes:
            raise ValueError(
                f"chart {chart_id}: edge {e['from']}->{e['to']} references an unknown node")
        if e.get("kind") == "cable":
            cables.append(e)
        elif e["from"] in parent:
            raise ValueError(
                f"chart {chart_id}: node {e['from']} has more than one tree parent")
        else:
            parent[e["from"]] = e["to"]

    # Sibling order = the order children appear in the nodes list.
    children: dict[str, list[str]] = {nid: [] for nid in nodes}
    for nid in nodes:
        if nid in parent:
            children[parent[nid]].append(nid)
    roots = [nid for nid in nodes if nid not in parent]

    if overlay:
        bands, size = _overlay_layout(chart_id, nodes, parent, overlay)
        annotations = list(overlay.get("annotations") or [])
    else:
        bands, size = _house_layout(chart_id, spec, nodes, children, roots)
        annotations = []
    max_x, max_y = size

    for n in nodes.values():
        n["vertical"] = n["h"] > 1.8 * n["w"]
        # Shrink the label font when it would overflow the box (PDF boxes are
        # not sized to our font); textLength pins the fit exactly.
        avail = (n["h"] if n["vertical"] else n["w"]) - 6
        est = CHAR_W * len(n["label"])  # width at font-size 10
        if est > avail > 0:
            n["font"] = round(max(7.0, 10.0 * avail / est), 1)
            n["squeeze"] = round(avail, 1)
    annotations += [
        {"x": n["x"] + n["w"] + 6, "y": n["cy"], "text": n["note"]}
        for n in nodes.values() if n.get("note")
    ]

    arrows = []
    if overlay:
        for c, p in parent.items():
            arrows.append({"color": "#000000", "marker": True,
                           "points": _route(nodes[c], nodes[p])})
        for i, e in enumerate(cables):
            s, t = nodes[e["from"]], nodes[e["to"]]
            if abs(s["cx"] - t["cx"]) > 500:
                # long haul: drop to a bottom corridor like the PDF's own
                # cross-chart cable runs, then rise into the target
                corridor = max_y - 14 - (i % 5) * 6
                points = [(s["cx"], s["y"] + s["h"]), (s["cx"], corridor),
                          (t["cx"], corridor), (t["cx"], t["y"] + t["h"])]
            else:
                points = _route(s, t)
            arrows.append({"color": e.get("color", "#ff0000"), "marker": True,
                           "points": points})
    else:
        # Bracket connectors: one arrowed trunk into the parent, plain stubs
        # from each child; cables route through a staggered lane at the right.
        for p, kids in children.items():
            if not kids:
                continue
            pn, last = nodes[p], nodes[kids[-1]]
            tx, py = pn["x"] + TRUNK_X, pn["y"] + BOX_H
            arrows.append({"color": "#000000", "marker": True,
                           "points": [(tx, last["cy"]), (tx, py)]})
            for c in kids:
                cn = nodes[c]
                arrows.append({"color": "#000000", "marker": False,
                               "points": [(cn["x"], cn["cy"]), (tx, cn["cy"])]})
        for i, e in enumerate(cables):
            s, t = nodes[e["from"]], nodes[e["to"]]
            lane = max(s["x"] + s["w"], t["x"] + t["w"]) + CABLE_LANE + (i % 6) * LANE_STEP
            max_x = max(max_x, lane)
            arrows.append({"color": e.get("color", "#ff0000"), "marker": True,
                           "points": [(s["x"] + s["w"], s["cy"]), (lane, s["cy"]),
                                      (lane, t["cy"]), (t["x"] + t["w"], t["cy"])]})
    for a in arrows:
        a["path"] = " ".join(f"{x:g},{y:g}" for x, y in a["points"])
        a["color_key"] = a["color"].lstrip("#")

    meta = spec.get("chart") or {}
    return {
        "id": chart_id,
        "title": meta.get("title", chart_id),
        "source": meta.get("source", ""),
        "width": max_x + (0 if overlay else MARGIN),
        "height": max_y + (0 if overlay else MARGIN),
        "bands": bands,
        "boxes": [n for n in nodes.values()],
        "annotations": annotations,
        "arrows": arrows,
        "arrow_colors": sorted({(a["color_key"], a["color"]) for a in arrows}),
    }


def _overlay_layout(chart_id, nodes, parent, overlay):
    """PDF-faithful placement from the generated layout overlay. Spec nodes
    missing from the overlay (hand-added before the next PDF) stack under
    their parent as a visible draft placement."""
    geo = overlay.get("nodes") or {}
    orphans = []
    for nid, n in nodes.items():
        g = geo.get(nid)
        if g:
            n.update(x=g["x"], y=g["y"], w=g["w"], h=g["h"],
                     cx=g["x"] + g["w"] / 2, cy=g["y"] + g["h"] / 2)
        else:
            orphans.append(nid)
    for _ in range(3):  # parents may themselves be orphans; a few passes
        for nid in list(orphans):
            pn = nodes.get(parent.get(nid))
            if pn and "x" in pn:
                k = orphans.index(nid)
                w = _box_w(nodes[nid]["label"])
                nodes[nid].update(
                    x=pn["x"] + INDENT, y=pn["y"] + (k + 1) * (BOX_H + VGAP),
                    w=w, h=BOX_H, cx=pn["x"] + INDENT + w / 2,
                    cy=pn["y"] + (k + 1) * (BOX_H + VGAP) + BOX_H / 2)
                orphans.remove(nid)
    for k, nid in enumerate(orphans):  # no placed parent: corner stack
        w = _box_w(nodes[nid]["label"])
        nodes[nid].update(x=MARGIN, y=MARGIN + k * (BOX_H + VGAP), w=w, h=BOX_H,
                          cx=MARGIN + w / 2, cy=MARGIN + k * (BOX_H + VGAP) + BOX_H / 2)

    bands = [{"label": b.get("label"), "fill": b.get("fill"),
              "y": b["y0"], "h": b["y1"] - b["y0"],
              "label_x": b.get("label_x", 30),
              "label_y": b.get("label_y", b["y0"] + 24)}
             for b in overlay.get("bands") or []]
    canvas = overlay.get("canvas") or {}
    return bands, (canvas.get("width", 1920), canvas.get("height", 1080))


def _house_layout(chart_id, spec, nodes, children, roots):
    """Computed layout in the chart's idiom, for charts with no overlay."""
    max_x = 0.0

    def place(nid: str, x: float, y: float) -> tuple[float, float]:
        """Position nid's subtree; returns (height, right edge) incl. notes."""
        nonlocal max_x
        n = nodes[nid]
        n.update(x=x, y=y, w=_box_w(n["label"]), h=BOX_H,
                 cx=x + _box_w(n["label"]) / 2, cy=y + BOX_H / 2)
        right = x + n["w"]
        if n.get("note"):
            right += 6 + NOTE_CHAR_W * len(str(n["note"]))
        cy = y + BOX_H + VGAP
        for c in children[nid]:
            sub_h, sub_right = place(c, x + INDENT, cy)
            cy += sub_h + VGAP
            right = max(right, sub_right)
        max_x = max(max_x, right)
        return cy - VGAP - y, right

    # Band rows, top to bottom. Roots without a band land in the last one.
    band_specs = spec.get("bands") or [{"id": None}]
    default_band = band_specs[-1].get("id")
    bands, y = [], MARGIN
    for band in band_specs:
        b_roots = [r for r in roots
                   if nodes[r].get("band", default_band) == band.get("id")]
        if b_roots:
            x = MARGIN + (LABEL_W if band.get("label") else 0)
            row_h = 0.0
            for r in b_roots:
                h, right = place(r, x, y + BAND_PAD)
                x = right + ROOT_GAP
                row_h = max(row_h, h)
            band_h = row_h + 2 * BAND_PAD
        else:
            band_h = EMPTY_BAND_H
        bands.append({**band, "y": y, "h": band_h, "label_y": y + 24})
        y += band_h

    unplaced = [nid for nid, n in nodes.items() if "x" not in n]
    if unplaced:
        raise ValueError(
            f"chart {chart_id}: unreachable nodes (edge cycle?): "
            f"{', '.join(sorted(unplaced))}")
    return bands, (max_x, y)
