from django.urls import path
from django.views.generic.base import RedirectView

from . import views

app_name = "explore"

urlpatterns = [
    path("", views.explore_tree_view, name="home"),
    path("tree/", views.explore_tree_view, name="tree"),
    path("browse/", views.explore_view, name="browse"),
    path("hierarchy/", views.explore_hierarchy_view, name="hierarchy"),
    path("hierarchy/summary/", views.explore_type_summary_view, name="type_summary"),
    path("type-positions/<str:part_type_id>/", views.explore_type_positions_view,
         name="type_positions"),
    path("type-locations/<str:part_type_id>/", views.explore_type_locations_view,
         name="type_locations"),
    path("shipments/", views.shipments_view, name="shipments"),
    path("shipments/search/", views.explore_shipments_search_api_view,
         name="shipments_search_api"),
    path("activities/", views.explore_activities_view, name="activities"),
    path("watch/", views.explore_watch_toggle_view, name="watch_toggle"),
    path("watch/seen/", views.explore_watch_seen_view, name="watch_seen"),
    path("search/", views.explore_search_view, name="search"),
    path("search/api/", views.explore_search_api_view, name="search_api"),
    path("docs/", views.explore_docs_view, name="docs"),
    path("institutions/", views.explore_institutions_view, name="institutions"),
    path("lookup/<str:part_id>/", views.explore_lookup_view, name="lookup"),
    path("checklist-map/<str:part_id>/", views.explore_checklist_map_view, name="checklist_map"),
    path("pid-list/<str:part_type_id>/", views.explore_pid_list_view, name="pid_list"),
    path("scan/", views.explore_scan_view, name="scan"),
    path("scan/submit/", views.explore_scan_submit_view, name="scan_submit"),
    path("scan/feed/", views.explore_scan_feed_view, name="scan_feed"),
    path("box-create/<str:part_type_id>/", views.explore_box_create_view,
         name="box_create"),
    path("shipping-type/<str:part_type_id>/", views.explore_shipping_type_toggle_view,
         name="shipping_type_toggle"),
    path("box-type/<str:part_type_id>/", views.explore_box_type_view,
         name="box_type"),
    path("es-config/<str:part_type_id>/", views.explore_es_config_view,
         name="es_config"),
    path("checklist-config/<str:part_type_id>/",
         views.explore_checklist_config_view, name="checklist_config"),
    path("checklist-config/<str:part_type_id>/preview/",
         views.explore_checklist_preview_view, name="checklist_preview"),
    path("checklist-config/<str:part_type_id>/asset/",
         views.explore_checklist_asset_view, name="checklist_asset"),
    path("part-new/<str:part_type_id>/", views.explore_item_create_view,
         name="item_create"),
    path("checklist/<str:part_type_id>/<str:name>/",
         views.explore_type_checklist_view, name="type_checklist"),
    path("checklist-names/<str:part_type_id>/",
         views.explore_checklist_names_view, name="checklist_names"),
    path("checklist-bookmark/", views.explore_checklist_bookmark_view,
         name="checklist_bookmark"),
    path("profile/", views.explore_profile_view, name="profile"),
    path("login/", views.login_view, name="login"),
    path("login/poll/", views.login_poll_view, name="login_poll"),
    path("sync/", views.explore_sync_view, name="sync"),
    path("sync-tests/<str:part_type_id>/", views.explore_node_sync_view, name="node_sync"),
    path("sync-system/<int:system_id>/", views.explore_system_sync_view, name="system_sync"),
    path("sync-shipments/<str:part_type_id>/", views.explore_shipment_sync_view, name="shipment_sync"),
    path("shipment-image/<str:image_id>/", views.explore_shipment_image_view, name="shipment_image"),
    path("test-data/<str:part_id>/<str:test_type_id>/", views.explore_test_data_view, name="test_data"),
    path("part/<str:part_id>/", views.explore_part_view, name="part"),
    path("part/<str:part_id>/location/", views.explore_part_location_view,
         name="part_location"),
    path("part/<str:part_id>/pack/", views.explore_box_pack_view, name="box_pack"),
    path("part/<str:part_id>/edit/", views.explore_part_edit_view, name="part_edit"),
    path("part/<str:part_id>/spec-delete/", views.explore_spec_delete_view,
         name="spec_delete"),
    path("part/<str:part_id>/refresh-shipment/", views.explore_shipment_refresh_view,
         name="shipment_refresh"),
    path("part/<str:part_id>/exec-summary/", views.explore_exec_summary_view,
         name="exec_summary"),
    path("part/<str:part_id>/exec-summary/plot/<int:index>/",
         views.explore_es_plot_view, name="es_plot"),
    path("part/<str:part_id>/es-subtree/", views.explore_es_subtree_view,
         name="es_subtree"),
    path("part/<str:part_id>/checklist/<str:name>/", views.explore_checklist_view,
         name="checklist"),
    path("part/<str:part_id>/preship/", views.explore_preship_view, name="preship"),
    path("part/<str:part_id>/shipping/", views.explore_shipping_view, name="shipping"),
    path("part/<str:part_id>/receiving/", views.explore_receiving_view, name="receiving"),
    path("assembly/<str:part_id>/", views.explore_assembly_view, name="assembly"),
    # The box page is now the generic part page (ADR-0014); keep old links working.
    path("shipment/<str:part_id>/",
         RedirectView.as_view(pattern_name="explore:part", permanent=True),
         name="shipment_detail"),
    # Drill-in node deep links (kept last so the specific routes above win).
    path("<path:trail>/", views.explore_view, name="node"),
]
