"""
Django settings for cets project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from decouple import config, Csv
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-(!6n$q0(7y7uxzih_0rzehcnmf)v35)9(k*&duk$2$u$vfy=0y'
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=Csv())

FORCE_SCRIPT_NAME = config("FORCE_SCRIPT_NAME", default=None)

# Tests must resolve URLs rooted at "/", not under FORCE_SCRIPT_NAME (which
# prod sets to /twister/cets). The runner neutralizes the prefix — see
# cets/test_runner.py for why.
TEST_RUNNER = "cets.test_runner.CetsTestRunner"

CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", default="", cast=Csv())

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "rest_framework",
    "django_filters",
    "django_extensions",
    # Your local apps
    "core",
    "users",
    "hwdb",
    "explore",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.auth.middleware.LoginRequiredMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
]

LOGIN_URL = (
    f"{FORCE_SCRIPT_NAME}/api-auth/login/" if FORCE_SCRIPT_NAME else "/api-auth/login/"
)
LOGIN_REDIRECT_URL = f"{FORCE_SCRIPT_NAME}/" if FORCE_SCRIPT_NAME else "/"

# hwdb (Fermilab hardware DB) target instance. One knob drives the API base,
# the external web-UI links, and the component part_type_id together (dev/prod
# differ by the cdbdev<->cdb path segment plus the part type; see the official
# dune_ce_hwdb.py). Defaults to prod.
HWDB_INSTANCE = config("HWDB_INSTANCE", default="prod")
HWDB_PROFILES = {
    "prod": {
        "api": "https://dbwebapi2.fnal.gov:8443/cdb/api/v1",
        "ui": "https://dbweb2.fnal.gov:8443/cdb",
        "larasic_part_type": "D08100100003",
        "coldadc_part_type": "D08100200002",  # coldadc_p2prb1
        "coldata_part_type": "D08100300003",  # coldata_e4prb2
    },
    "dev": {
        "api": "https://dbwebapi2.fnal.gov:8443/cdbdev/api/v1",
        "ui": "https://dbweb2.fnal.gov:8443/cdbdev",
        "larasic_part_type": "D08100100004",
        "coldadc_part_type": "D08100200001",  # coldadc_p2prep
        "coldata_part_type": "D08100300001",  # coldata_e4prep
    },
}
if HWDB_INSTANCE not in HWDB_PROFILES:
    raise ImproperlyConfigured(
        f"HWDB_INSTANCE must be one of {sorted(HWDB_PROFILES)}; got {HWDB_INSTANCE!r}"
    )
# Default-instance values (the env baseline). A per-session override may pick a
# different profile at request time — see hwdb.instance.active_profile.
HWDB_API_BASE_URL = HWDB_PROFILES[HWDB_INSTANCE]["api"]
HWDB_UI_BASE_URL = HWDB_PROFILES[HWDB_INSTANCE]["ui"]
HWDB_LARASIC_PART_TYPE = HWDB_PROFILES[HWDB_INSTANCE]["larasic_part_type"]

# Per-component-type defaults for HWDB upload (Phase-3). Manufacturers and
# institutions are per-part-type; LArASIC is BNL/TSMC. Add new entries as we
# fan out to FEMB/ColdADC/COLDATA/Cable.
HWDB_COMPONENT_DEFAULTS = {
    "larasic": {
        # TSMC manufacturer_id differs per HWDB instance (confirmed via
        # .idea/spike/hwdb_id_compare.py 2026-05-29). Other ids (BNL=128,
        # status=110) are shared. Any field whose value is a dict is treated
        # as per-instance and resolved by _larasic_defaults(instance).
        "manufacturer_id": {"prod": 15, "dev": 59},  # TSMC
        "institution_id": 128,     # BNL
        "country_code": "US",
        "warm_test_name": "RoomT QC Test",
        "cold_test_name": "CryoT QC Test",
        # status_id 110 = "Waiting on QA/QC Tests" (per Karla's note.md;
        # patched after RTS upload, refined by later QA/QC analysis).
        "initial_status_id": 110,
    },
}

ROOT_URLCONF = "cets.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "hwdb.context_processors.fnal_link",
            ],
        },
    },
]

WSGI_APPLICATION = "cets.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = "static/"
STATIC_URL = config("STATIC_URL", default="static/")
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# if DEBUG:
#     # Add django_browser_reload only in DEBUG mode
#     INSTALLED_APPS += ["django_browser_reload"]
