# Generated by Django 5.2.5 on 2026-06-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentTypeNode',
            fields=[
                ('part_type_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('project', models.CharField(default='D', max_length=4)),
                ('system_id', models.PositiveIntegerField(db_index=True)),
                ('system_name', models.CharField(max_length=100)),
                ('subsystem_id', models.PositiveIntegerField()),
                ('subsystem_name', models.CharField(max_length=100)),
                ('component_type_name', models.CharField(max_length=200)),
                ('full_name', models.CharField(blank=True, default='', max_length=300)),
                ('n_components', models.PositiveIntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('tests_synced_at', models.DateTimeField(blank=True, null=True)),
                ('n_tests', models.PositiveIntegerField(default=0)),
                ('tests_sync_error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['system_id', 'subsystem_id', 'component_type_name'],
            },
        ),
        migrations.CreateModel(
            name='HierarchySyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('systems_count', models.PositiveIntegerField(default=0)),
                ('nodes_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='HwdbComponentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type_id', models.CharField(db_index=True, max_length=20)),
                ('part_id', models.CharField(max_length=50)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['part_type_id', 'updated'], name='explore_hwd_part_ty_8951fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='HwdbTestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type_id', models.CharField(db_index=True, max_length=20)),
                ('part_id', models.CharField(max_length=50)),
                ('test_type_name', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['part_type_id', 'created'], name='explore_hwd_part_ty_f6307c_idx')],
            },
        ),
    ]
