# Generated by Django 5.2.5 on 2026-06-29 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_cets_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='HierarchyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('system', 'System'), ('subsystem', 'Subsystem'), ('component_type', 'Component type')], db_index=True, max_length=16)),
                ('project', models.CharField(default='D', max_length=4)),
                ('system_id', models.PositiveIntegerField(db_index=True)),
                ('system_name', models.CharField(max_length=100)),
                ('subsystem_id', models.PositiveIntegerField(blank=True, null=True)),
                ('subsystem_name', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('full_name', models.CharField(blank=True, default='', max_length=300)),
                ('part_type_id', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('n_components', models.PositiveIntegerField(default=0)),
                ('tests_synced_at', models.DateTimeField(blank=True, null=True)),
                ('n_tests', models.PositiveIntegerField(default=0)),
                ('tests_sync_error', models.TextField(blank=True, default='')),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='explore.hierarchynode')),
            ],
            options={
                'ordering': ['system_id', 'subsystem_id', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='ComponentTypeNode',
        ),
        migrations.AddIndex(
            model_name='hierarchynode',
            index=models.Index(fields=['level', 'system_id'], name='explore_hie_level_a3e24f_idx'),
        ),
    ]
