# Generated by Django 5.2.5 on 2026-06-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0003_hierarchynode_delete_componenttypenode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type_id', models.CharField(db_index=True, max_length=20)),
                ('part_id', models.CharField(max_length=50)),
                ('location_name', models.CharField(blank=True, default='', max_length=200)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('last_arrived', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['part_id'],
                'indexes': [models.Index(fields=['part_type_id'], name='explore_shi_part_ty_52ad77_idx')],
            },
        ),
    ]
