# Generated by Django 5.2.5 on 2026-06-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0004_shipmentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentitem',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='shipped_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
