# Generated by Django 5.2.5 on 2026-06-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0005_shipmentitem_received_date_shipmentitem_shipped_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentitem',
            name='n_contents',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
