# Generated by Django 5.2.5 on 2026-06-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0006_shipmentitem_n_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='hierarchynode',
            name='shipments_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
