# Generated by Django 5.2.5 on 2026-06-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0007_hierarchynode_shipments_synced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwdbcomponentevent',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='hwdbcomponentevent',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
