# Generated by Django 5.2.5 on 2026-06-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0008_hwdbcomponentevent_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwdbcomponentevent',
            name='institution',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='hwdbcomponentevent',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='hwdbcomponentevent',
            name='status',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
