# Generated by Django 5.2.5 on 2026-07-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0009_hwdbcomponentevent_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hierarchynode',
            name='instance',
            field=models.CharField(db_index=True, default='prod', max_length=8),
        ),
        migrations.AddField(
            model_name='hierarchysyncstate',
            name='instance',
            field=models.CharField(default='prod', max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='hwdbcomponentevent',
            name='instance',
            field=models.CharField(db_index=True, default='prod', max_length=8),
        ),
        migrations.AddField(
            model_name='hwdbtestevent',
            name='instance',
            field=models.CharField(db_index=True, default='prod', max_length=8),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='instance',
            field=models.CharField(db_index=True, default='prod', max_length=8),
        ),
    ]
