# Generated by Django 5.2.5 on 2026-07-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0010_hierarchynode_instance_hierarchysyncstate_instance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hierarchynode',
            name='structure_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
