# Generated by Django 5.2.5 on 2026-07-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0011_hierarchynode_structure_synced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwdbcomponentevent',
            name='certified_qaqc',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hwdbcomponentevent',
            name='is_installed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hwdbcomponentevent',
            name='qaqc_uploaded',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
