# Generated by Django 5.2.5 on 2026-07-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0012_hwdbcomponentevent_certified_qaqc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwdbcomponentevent',
            name='enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hwdbcomponentevent',
            name='parent_part_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
    ]
