# Generated by Django 5.2.5 on 2026-07-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0013_hwdbcomponentevent_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.CharField(db_index=True, default='prod', max_length=8)),
                ('part_id', models.CharField(db_index=True, max_length=50)),
                ('workflow', models.CharField(choices=[('preshipping', 'Pre-Shipping'), ('shipping', 'Shipping'), ('receiving', 'Receiving')], max_length=20)),
                ('route', models.CharField(choices=[('confirm_surf', 'Shipping to SURF'), ('confirm_non_surf', 'Shipping to non-SURF'), ('confirm_transshipping', 'Transshipping to SURF')], default='confirm_surf', max_length=24)),
                ('current_scene', models.PositiveSmallIntegerField(default=1)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('instance', 'part_id', 'workflow'), name='one_checklist_per_box_workflow')],
            },
        ),
    ]
