# Generated by Django 5.2.5 on 2026-07-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0015_packscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='hierarchynode',
            name='cable_ends',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hierarchynode',
            name='category',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
