# Generated by Django 5.2.5 on 2026-07-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0017_remap_obsolete_available_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwdbcomponentevent',
            name='status_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
