# Generated by Django 5.2.5 on 2026-08-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0019_packscan_box_part_id_packscan_ok_packscan_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.CharField(db_index=True, default='prod', max_length=8)),
                ('kind', models.CharField(max_length=12)),
                ('part_id', models.CharField(blank=True, default='', max_length=50)),
                ('part_type_id', models.CharField(blank=True, default='', max_length=20)),
                ('summary', models.TextField()),
                ('actor', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
