# Generated by Django 5.2.5 on 2026-08-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0020_activityevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.CharField(db_index=True, default='prod', max_length=8)),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('part_id', models.CharField(blank=True, default='', max_length=50)),
                ('part_type_id', models.CharField(blank=True, default='', max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('instance', 'username', 'part_id', 'part_type_id'), name='uniq_watch_per_user_target')],
            },
        ),
    ]
