# Generated by Django 5.2.5 on 2026-08-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0021_watchsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.CharField(db_index=True, default='prod', max_length=8)),
                ('part_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=120)),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('instance', 'part_id', 'name', 'username'), name='uniq_checklist_draft')],
            },
        ),
    ]
