# Generated by Django 5.2.5 on 2026-08-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0022_checklistdraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingTypeOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.CharField(db_index=True, default='prod', max_length=8)),
                ('part_type_id', models.CharField(db_index=True, max_length=20)),
                ('added_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('instance', 'part_type_id'), name='uniq_shipping_type_override')],
            },
        ),
    ]
