# Generated by Django 5.2.5 on 2026-09-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0023_shippingtypeoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.CharField(db_index=True, default='prod', max_length=8)),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('part_type_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['part_type_id', 'name'],
                'constraints': [models.UniqueConstraint(fields=('instance', 'username', 'part_type_id', 'name'), name='uniq_checklist_bookmark')],
            },
        ),
    ]
