# Generated by Django 5.2.5 on 2026-09-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0024_checklistbookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionPref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.CharField(db_index=True, default='prod', max_length=8)),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('institution_id', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('instance', 'username'), name='uniq_institution_pref')],
            },
        ),
    ]
