# Generated by Django 5.2.5 on 2026-09-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0025_institutionpref'),
    ]

    operations = [
        migrations.CreateModel(
            name='HwdbTestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.CharField(db_index=True, default='prod', max_length=8)),
                ('part_type_id', models.CharField(db_index=True, max_length=20)),
                ('part_id', models.CharField(max_length=50)),
                ('test_type_id', models.IntegerField()),
                ('test_type_name', models.CharField(max_length=100)),
                ('test_id', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('test_data', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['instance', 'part_type_id', 'test_type_id'], name='explore_hwd_instanc_8c69e1_idx')],
                'constraints': [models.UniqueConstraint(fields=('instance', 'part_id', 'test_type_id'), name='uniq_testdata_item_type')],
            },
        ),
    ]
