# Generated by Django 5.2.5 on 2026-09-11 18:53

from django.db import migrations, models

import json


def _values_at(node, segs, i=0):
    if isinstance(node, list):
        out = []
        for e in node:
            out.extend(_values_at(e, segs, i))
        return out
    if i == len(segs):
        return [node] if node is not None and not isinstance(node, (dict, list)) else []
    if isinstance(node, dict) and segs[i] in node:
        return _values_at(node[segs[i]], segs, i + 1)
    return []


def _flatten(node, prefix=(), out=None):
    """Inline copy of explore.plotting.flatten (migrations must not import
    app code that may change later)."""
    if out is None:
        out = {}
    if isinstance(node, dict):
        for k, v in node.items():
            _flatten(v, prefix + (str(k),), out)
    elif isinstance(node, list):
        if any(isinstance(e, dict) for e in node):
            for e in node:
                if isinstance(e, dict):
                    _flatten(e, prefix, out)
                elif e is not None and not isinstance(e, list) and prefix:
                    out.setdefault(prefix, []).append(e)
        elif prefix:
            vals = out.setdefault(prefix, [])
            for e in node:
                if isinstance(e, list):
                    vals.extend(_values_at(e, [], 0))
                elif e is not None:
                    vals.append(e)
    elif node is not None and prefix:
        out.setdefault(prefix, []).append(node)
    return out


def backfill(apps, schema_editor):
    """Value rows for records mirrored before the table existed (#143
    first deploy); batched so a 30k-record mirror doesn't load at once."""
    HwdbTestData = apps.get_model("explore", "HwdbTestData")
    HwdbTestValue = apps.get_model("explore", "HwdbTestValue")
    last = 0
    while True:
        batch = list(HwdbTestData.objects.filter(pk__gt=last).order_by("pk")[:500])
        if not batch:
            break
        rows = []
        for r in batch:
            for path, vals in _flatten(r.test_data).items():
                if vals:
                    rows.append(HwdbTestValue(
                        instance=r.instance, part_type_id=r.part_type_id, part_id=r.part_id,
                        test_type_id=r.test_type_id, path=json.dumps(list(path)), values=vals, nv=len(vals)))
        HwdbTestValue.objects.bulk_create(rows, batch_size=1000)
        last = batch[-1].pk



class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0026_hwdbtestdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='HwdbTestValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.CharField(db_index=True, default='prod', max_length=8)),
                ('part_type_id', models.CharField(max_length=20)),
                ('part_id', models.CharField(max_length=50)),
                ('test_type_id', models.IntegerField()),
                ('path', models.TextField()),
                ('values', models.JSONField(blank=True, default=list)),
                ('nv', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['instance', 'part_type_id', 'test_type_id', 'path'], name='idx_testvalue_key'), models.Index(fields=['instance', 'part_id', 'test_type_id'], name='idx_testvalue_item')],
            },
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
