# Generated by Django 5.2.5 on 2026-09-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0028_rebuild_test_values_nested'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistdraft',
            name='pending_error',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='checklistdraft',
            name='pending_post',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
