# Generated by Django 5.2.5 on 2026-09-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0029_checklistdraft_pending'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDateSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.CharField(db_index=True, default='prod', max_length=8)),
                ('part_type_id', models.CharField(db_index=True, max_length=20)),
                ('path', models.JSONField(default=list)),
                ('style', models.CharField(choices=[('ymd', 'YYYY-MM-DD / YYYY/MM/DD'), ('dm-or-md', 'DD-MM-YYYY or MM-DD-YYYY (each record settles itself)')], default='ymd', max_length=12)),
                ('day_first', models.BooleanField(default=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('instance', 'part_type_id'), name='uniq_test_date_setting')],
            },
        ),
    ]
