# Generated by Django 5.2.5 on 2026-09-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0030_testdatesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildMintSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.CharField(db_index=True, default='prod', max_length=8)),
                ('part_type_id', models.CharField(db_index=True, max_length=20)),
                ('children', models.JSONField(default=list)),
                ('updated_by', models.CharField(blank=True, default='', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('instance', 'part_type_id'), name='uniq_child_mint_setting')],
            },
        ),
    ]
