# Generated by Django 5.2.5 on 2026-09-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0031_childmintsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='packscan',
            name='target',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
