# Generated by Django 5.2.5 on 2026-09-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0032_packscan_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.CharField(db_index=True, default='prod', max_length=8)),
                ('part_type_id', models.CharField(db_index=True, max_length=20)),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('name', models.CharField(max_length=200)),
                ('tabs', models.JSONField(blank=True, default=list)),
                ('sheet', models.JSONField(blank=True, default=dict)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('rows', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
