# Generated by Django 5.2.5 on 2026-09-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0033_sheetjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetjob',
            name='kind',
            field=models.CharField(default='item', max_length=8),
        ),
        migrations.AddField(
            model_name='sheetjob',
            name='test_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
