# Generated by Django 5.2.5 on 2026-09-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0034_sheetjob_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hwdbtestdata',
            name='test_data',
        ),
        migrations.AddField(
            model_name='hwdbtestvalue',
            name='shape',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
