# Generated by Django 5.2.5 on 2026-10-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0035_testdata_drop_blob_testvalue_shape'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('day', models.DateField()),
                ('requests', models.PositiveIntegerField(default=0)),
                ('last_seen', models.DateTimeField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('username', 'day'), name='usageday_username_day')],
            },
        ),
    ]
