# Generated by Django 5.2.5 on 2026-10-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0036_usageday'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.CharField(db_index=True, default='prod', max_length=8)),
                ('part_type_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('source_type_id', models.CharField(db_index=True, max_length=20)),
                ('source_part_id', models.CharField(max_length=50)),
                ('checklist', models.CharField(blank=True, default='', max_length=200)),
                ('component', models.CharField(blank=True, default='', max_length=200)),
                ('needed', models.IntegerField(blank=True, null=True)),
                ('completed_by', models.CharField(blank=True, default='', max_length=7)),
                ('needed_by', models.CharField(blank=True, default='', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source_part_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConsortiumTypeOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.CharField(db_index=True, default='prod', max_length=8)),
                ('part_type_id', models.CharField(db_index=True, max_length=20)),
                ('added_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('instance', 'part_type_id'), name='uniq_consortium_type_override')],
            },
        ),
        migrations.CreateModel(
            name='ProductionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.CharField(db_index=True, default='prod', max_length=8)),
                ('source_type_id', models.CharField(db_index=True, max_length=20)),
                ('source_part_id', models.CharField(max_length=50)),
                ('checklist', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('serial', models.CharField(blank=True, default='', max_length=120)),
                ('instructions', models.TextField(blank=True, default='')),
                ('columns', models.JSONField(default=list)),
                ('rows', models.JSONField(default=list)),
                ('as_of', models.CharField(blank=True, default='', max_length=40)),
                ('read_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source_type_id', 'source_part_id', 'checklist'],
                'constraints': [models.UniqueConstraint(fields=('instance', 'source_part_id', 'checklist'), name='uniq_production_table')],
            },
        ),
    ]
