# Generated by Django 5.2.5 on 2026-10-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0038_production_plan_per_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwdbtestevent',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
